### ISSUE TITLE
Is it possible to use this file with windows .iso?

### ISSUE THREAD

**Issue by PanPeople** [padthaitofuhot/bootia32-efi#1]
Is it possible to use this file with windows .iso?
Only GRUB console appeared and error when i try tu manually run .efi files but maybe i am missing something

**Comment by ghost** [comment]
No it's only for GRUB, I tried the same but it doesn't work

**Comment by GripAll** [comment]
Can anybody help me installing lubuntu on Lenovo Yoga Tab2 I tried installing WayDroid but some things broke.
So I have no idea how to start installing by tutorial if somebody could help I would appreciate it.

**Comment by ghost** [comment]
you already took a look here? https://askubuntu.com/questions/659806/install-ubuntu-desktop-or-touch-on-lenovo-yoga-tablet-2-windows-or-android
